// <auto-generated />
namespace PruebaDALE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _041329112022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_041329112022));
        
        string IMigrationMetadata.Id
        {
            get { return "202211290913288_041329112022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
